import bst
import wavl

print("<<<<<<<<<<<<<<<<<<<< BST TESTS >>>>>>>>>>>>>>>>>>>>>>>")
b = bst.BST()
b.insert(5)
b.insert(1)
b.insert(7)
b.insert(2)
b.insert(6)
b.insert(12)
b.insert(4)
b.insert(0)
b.insert(11)
b.insert(13)
b.insert(14)
b.insert(15)
b.insert(16)
b.insert(17)
b.insert(18)
b.insert(19)
b.inorder()
print(b.height())
print(b.search(1))
print(b.search(5))
print(b.search(7))
print(b.search(9))

print("<<<<<<<<<<<<<<<<<<<< WAVL TESTS >>>>>>>>>>>>>>>>>>>>>>>")
w = wavl.WAVL()
w.insert(5)
w.insert(1)
w.insert(7)
w.insert(2)
w.insert(6)
w.insert(12)
w.insert(4)
w.insert(0)
w.insert(11)
w.insert(13)
w.insert(14)
w.insert(15)
w.insert(16)
w.insert(17)
w.insert(18)
w.insert(19)

w.inorder_debug()
print(w.height())
print(w.search(1))
print(w.search(5))
print(w.search(7))
print(w.search(9))
